<?php



$cv = array(
    1 => array(
        "ime" => "Brian",
        "prezime" =>"Dobreski",
        "fotka" => "Brian_Dobreski_Photo.jpg",
        "cv" => "Brian Dobreski is an Assistant Professor in the School of Information Sciences at University of Tennessee-Knoxville. His research focuses on the social implications of metadata, resource description, and other knowledge organization practices, as well as the concepts of personhood and personal identity in information. Brian received his Ph.D. in information science from Syracuse University. He has authored works in publications including Journal of Documentation, Knowledge Organization, Cataloging & Classification Quarterly, and the ISKO Encyclopedia. His dissertation, Values in Knowledge Organization Standards: A Value Analysis of RDA, received an honorable mention for the ProQuest Best Dissertation Award, as well as Runner Up for the iSchools 2020 Doctoral Dissertation Award.
"),
    2 => array(
        "ime" => "Giulia Carla",
        "prezime" =>"Rossi",
        "fotka" => "Giulia_Carla_Rossi_Photo.png",
        "cv" => "Giulia Carla Rossi works as Curator for Digital Publications at the British Library in London, UK. She is responsible for supporting the Library in developing capacity to manage collections of complex digital objects as part of the Emerging Formats Project. Currently, the project is focussing on publications produced for mobile devices (apps) and interactive narratives, covering requirements across the collection management lifecycle. She is interested in interactive storytelling, net art and how new forms of creating and consuming content are challenging existing practices in collecting institutions. 
She has a background in digital publishing and previously worked in Editorial and Production roles at different academic and trade publishers."),
    3 => array(
        "ime" => "Alison ",
        "prezime" =>"Hicks ",
        "fotka" => "Hicks_Alison_photo.jpg",
        "cv" => "Dr Alison Hicks is Programme Director of Library and Information Studies and Lecturer (Assistant Professor) at the Department of Information Studies at UCL. Alison’s research focuses on sociocultural approaches to information literacy, including in relation to risk, transition, and most recently, health literacy. Her work has appeared in the Journal of Documentation, the Journal of Librarianship and Information Science and the Journal of Information Science, amongst others.  "),
    4 => array(
        "ime" => "Maja",
        "prezime" =>"Žumer",
        "fotka" => "Maja_Zumer_photo.jpg",
        "cv" => "Dr. Maja Žumer is Professor of Information Science at University of Ljubljana (Slovenia). Her research interests include design and evaluation of information retrieval systems, end-user interfaces, usability, and conceptual modelling. She was member of IFLA FRBR Review Group and co-chair of FRSAD Woking Group and has published extensively on the topic. As a member of the Consolidation Editorial Group she is co-author of IFLA LRM (with Pat Riva and Patrick LeBoeuf). She was IFLA Division 3 Chair and member of IFLA Professional Committee and Governing Board."),
    5 => array(
        "ime" => "Tali",
        "prezime" =>"Gazit",
        "fotka" => "Tali Gazit 2020.jpg",
        "cv" => "Tali Gazit is an Assistant Professor and a senior faculty member in the Department of Information Science, Bar-Ilan University (Israel). She received her Ph.D. in Internet Psychology from the Department of Information Science, Bar-Ilan University, Israel. Her research interests are psychological and environmental factors of engagement and lurking in online discussions, social media groups and communities, well-being and Internet, virtual leaders, and information literacy. She is also interested in older adults and technology, online romantic relationships, and the academic engagement of students who were suddenly forced to study online during the COVID-19 pandemic. She has published articles in information and psychological journals, reviewed manuscripts for respected journals and conferences, and presented her studies in various international information, psychological and communication conferences.
Tali Gazit, PhD
The Department of Information Science
Bar-Ilan University, Israel
Email: tal.gazit@biu.ac.il"),
    6 => array(
        "ime" => "Frida ",
        "prezime" =>"Bišćan",
        "fotka" => "Frida_Biscan_photo.jpg",
        "cv" => "Frida Bišćan, library adviser, works in the Croatian Institute for Librarianship (Center for Libraries and Librarianship Development) at the National and University Library in Zagreb as a consultant for the school libraries. 
Her field of interest are history, work and activities of public and school libraries. 
She is a member of the The Permanent Board for Maintenance and Development of the online System of Unique Library Performance Electronic Statistical Data Collecting (http://hk.nsk.hr). In the Training Centre for Continuing Education of Librarians in Croatia she holds courses and workshops for librarians.
She actively participates in a work of the Croatian Library Association, helping with organization and participating at expert meetings, conferences and workshops in Croatia and abroad. She is the author and co-author of several published books and scientific articles. In the past ten years she created and led three international projects co-financed by the European Union."),
    7 => array(
        "ime" => "Sanjica",
        "prezime" =>"Faletar Tanacković",
        "fotka" => "Sanjica Faletar Tanackovic_fotkaCB.jpg",
        "cv" => "Sanjica Faletar Tanacković is a Professor at Department of Information Sciences, Faculty of Humanities and Social Sciences (FFHS), University of Osijek (UNIOS), Croatia. She obtained her PhD in Information science (2009) from University of Zagreb, Croatia. Her research interests include library services to the underserved and marginalized (prisoners, people with Alzheimer Disease, people with dyslexia etc.) and their information needs and behaviour, LIS education and library architecture. She participated in several projects: EU FP6 Coordination action CALIMERA (Cultural Applications: Local Institutions Mediating Electronic Resource Access), COST Action ARKWORK (Archeological Practices and Knowledge Work In the Digital Environment), Erasmus+ project EINFOSE (European Information Sciences Education: Encouraging Mobility and Learning Outcomes Harmonization) and DECRIS (Digital Education for Crisis Situations: Times when there is no alternative). She was a PI in the UNIOS project \"Information Needs of Alzheimer Patients and Their Caregivers\". She served as a President of the Croatian Reading Association (2006-2008) and is a co-director for the biennial international conference Libraries in the Digital Age (LIDA). She is the recepient of the Ljerka Markić Čučuković Award, awarded to the best LIS student at University of Zagreb (2000), the Croatian Librarians' Association (CLA) award Eva Verona which is presented to best young LIS professionals (2006), and FFHS Excellence in Research Award (2021)."),
    8 => array(
        "ime" => "Dunja Marija",
        "prezime" =>"Gabriel",
        "fotka" => "Dunja Marija Gabriel_fotka.png",
        "cv" => "Dunja Marija Gabriel is library advisor and consultant for public libraries in Croatian Institute for Librarianship (Center for Libraries and Librarianship Development) at National and University Library in Zagreb. She is a member of the Permanent Board for Maintenance and Development of the System of Unique Library Performance Electronic Statistical Data Collecting (http://hk.nsk.hr). In the Training Centre for Continuing Education of Librarians in Croatia she holds courses and workshops for Librarians. 
She is member of Croatian Library Association (CLA), member of Professional Board of CLA, head of Croatian Public Libraries Section and member of Croatian Section for Library Services to People with Special Needs. She is co-chair of the National Campaign for Persons with Reading Difficulties and Dyslexia „I Wish to Read Too!“ (2016.-2021.) organized by Croatian Library Association in cooperation with National and University Library in Zagreb and Zagreb City Libraries.
She was Standing Committee member of IFLA/LSN Section for Library Services to People with Special Needs and author and co-author of several presentations and papers held on IFLA Conferences and World Libray and Information Congresses.   
She publishes professional and scientific papers, organizes professional conferences and congresses (including biannual Croatian Conference on Public Libraries) and cooperates with numerous international professional experts to improve the work of public libraries in Croatia. 
"),
    9 => array(
        "ime" => "Lana",
        "prezime" =>"Šuster",
        "fotka" => "Lana_Suster_Photo.jpg",
        "cv" => "Lana Šuster, Head of Library at the Faculty of Humanities and Social Sciences in Osijek, University of Osijek. Graduated in Librarianship and Croatian Language and Literature at the Faculty of Humanities and Social Sciences in Osijek. Uses the experience of working in a library to investigate, among other things, the communication between the user and the librarian despite the digital changes that distance the user from verbal communication. Inspired by creative students at the Faculty, she sees the Library as a place of birth of the idea of associating all study programs at the Faculty in the world of art, a place of socializing through the students' word. Jorge Luis Borges' thought that \"The library will endure; it is the universe…\" can really put a university library at the center of events. The rhythm a library can offer is a change that a user can accept."),
    10 => array(
        "ime" => "Bo",
        "prezime" =>"Skøtt",
        "fotka" => "Bo_Skott_photo.png",
        "cv" => "Bo Skøtt is an associate professor at the Department of design and communication at University of southern Denmark in Kolding. He holds a Ph.D.- degree in library science and has been a researcher for 17 years at various research institutions in Denmark. His research interests include the public library and its significance in an overall societal context, including the institution’s political, social, and ecological contributions in times of upheaval. Bo Skøtt has studied the special form of communication referred to as dissemination, which takes place in Danish and foreign library and cultural institutions. He has studied the ongoing digitisation of the Danish public libraries and its significance for the Danish population’s sociality and democratic cohesion - and he has studied the public libraries’ significance as a social, political and cultural institution in connection with integration and reintegration of various target groups."),
    11 => array(
        "ime" => "Barbara",
        "prezime" =>"Kwaśnik",
        "fotka" => "Barbara_Kwasnik.photo.png",
        "cv" => "Barbara H. Kwaśnik, Professor Emerita, taught in the areas of knowledge organization and representation, theory of classification, and information science. Her main research interests are formal aspects of classification structure, personal information management, and the intersection of classification with everyday human endeavor. One of the most rewarding aspects of her career has been work with doctoral students, where she contributed the understanding of classification to the research process at all levels, from conceptualization to analysis. She retired in 2018 from the School of Information Studies at Syracuse University in Syracuse, N.Y., USA, but believes one never retires from engagement with students. Her publication, “Changing Perspectives on Classification as a Knowledge-Representation Process” (Knowl. Org. 46 (2019) No.8) summarizes the evolution of her thinking about classification over the past forty years. Feel free to contact her at bkwasnik@syr.edu ."),
    12 => array(
        "ime" => "Aleksandra",
        "prezime" =>"Pikić",
        "fotka" => "Aleksandra_Pikic.jpg",
        "cv" => "Aleksandra Pikić, PhD is a Library Adviser and Scientific Associate at the Croatian Institute for Librarianship of the National and University Library in Zagreb. She works as a national library adviser for Croatian academic and special libraries. She is an editorial board member of the Croatian scientific and professional library journal Vjesnik bibliotekarstva Hrvatske. She has authored and co-authored scientific and professional papers in Croatian and international journals. She has been an active member of the Croatian Library Association (CLA), in particular Commission for Library Statistics and Performance Indicators in Libraries and Commission for Higher Education Libraries. She is coordinator of the The Permanent Board for Maintenance and Development of the online System of Unique Library Performance Electronic Statistical Data Collecting. Her field of interest are user research, library statistics and performance indicators in libraries, bibliometrics and academic and special libraries."),
    13 => array(
        "ime" => "Jela",
        "prezime" =>"Steinerová",
        "fotka" => "Jela_Steinerova_photo.png",
        "cv" => "Jela Steinerová is Professor at the Department of Library and Information Science, Comenius University in Bratislava, Slovakia. Her research interests cover human information behaviour, information ecology and theory and methodology of information science. She has been teaching information science since 1992. She has headed several research projects (VEGA, APVV, DELOS) and published several monographs. Professor Steinerová has published widely in national and international journals, presented at international conferences and has been a member of several international editorial and conference boards and projects (e.g. ENWI, ECIL, ISIC, CoLIS,  Information Research). Since 2010 she has regularly organized international conferences on Information Interactions. Her current research topics include information ethics and information behaviour in digital environment. Her recent monographs present topics of information environment (2018) and an explanatory dictionary of Information Science (2020). She is the editor of the Annual Review of LIS of  Comenius University in Bratislava.
Comenius University in Bratislava
Department of Library and Information Science
Faculty of Arts,
Gondova 2
811 02 Bratislava
Slovak Republic
jela.steinerova@uniba.sk"),
    14 => array(
        "ime" => "Laura",
        "prezime" =>"Costello",
        "fotka" => "Laura Costello Photo.JPG",
        "cv" => "Laura Costello is the Information and Research Services Coordinator at Rutgers, The State University of New Jersey. In this role she coordinates virtual reference services, access services, and instructional services across the four major campuses at Rutgers. Prior to this position, she held positions at Stony Brook University and Teachers College, Columbia University in user services and materials acquisitions. She holds an MLIS from the University of Wisconsin and is currently pursuing a PhD in Library and Information Sciences at Rutgers' School of Communication & Information. "),
    15 => array(
        "ime" => "Virginia",
        "prezime" =>"Tucker",
        "fotka" => "Virginia_Tucker_photo.jpg",
        "cv" => "Virginia M. Tucker is assistant professor at the School of Information, San José State University, San Jose, California, USA. Her research and teaching interests are in information retrieval system design, advanced search, and information architecture. Tucker was previously product architect and training manager at Dialog/Thomson (now ProQuest), the physics librarian at Stanford University, and a public law librarian. She has a PhD in information systems from Queensland University of Technology, Brisbane, Australia; MLS from University of California at Berkeley; and a BA in music from Stanford University."),
    16 => array(
        "ime" => "Gordana",
        "prezime" =>"Gašo",
        "fotka" => "Gaso_photo.jpg",
        "cv" => "Gordana Gašo is a senior librarian at the Faculty of Humanities and Social Sciences, Osijek (Croatia). She is a PhD student at the University of Zadar, Croatia. She is an active member of the Croatian library community and a member of the working group DABAR - Digital Academic Archives and Repositories (from 2019) and the associate member of the Croatian Librarians Association Committee (from 2020).
Her areas of interest are user information behavior, open access and copyright in the context of institutional repositories and bibliometrics. 
She has published several professional and scholarly papers in foreign and domestic publications and has attended professional and scholarly conferences."),
    17 => array(
        "ime" => "Amy",
        "prezime" =>"VanScoy",
        "fotka" => "Amy_VanScoy_photo.jpeg",
        "cv" => "Amy VanScoy is an associate professor in the Department of Information Science at the University at Buffalo. Her research focuses on professional work, including practitioner thinking; diversity, equity, and inclusion issues; and the application of theory to library practice. She teaches courses in information behavior and research methods. She holds a PhD from the University of North Carolina at Chapel Hill. She publishes in journals such as Library & Information Science Research and Journal of Documentation and presents at national and international conferences."),
    18 => array(
        "ime" => "Ines",
        "prezime" =>"Horvat",
        "fotka" => "win_ines.jpg",
        "cv" => "Ines Horvat is a teaching and research assistant at the Department of Information Sciences, Faculty of Humanities and Social Sciences Osijek, University of Josip Juraj Strossmayer in Osijek. She is enrolled in the PhD program at the University of Zadar. The topic of her dissertation will address the methodological framework of written heritage preservation. Her areas of interest are preservation of analog and digital materials, heritage studies and written heritage interpretation."),
    19 => array(
        "ime" => "Sei-Ching Joanna",
        "prezime" =>"Sin",
        "fotka" => "SCJoanna_Sin_Photo.jpg",
        "cv" => "Sei-Ching Joanna Sin is an associate professor at the Wee Kim Wee School of Communication and Information, Nanyang Technological University, Singapore. She holds a Ph.D. and a master's degree in library and information studies from the University of Wisconsin—Madison. She received her Bachelor of Social Science degree from the Chinese University of Hong Kong, majored in Geography and minored in Anthropology. Her research interests include structural and individual factors in information behavior; perception, use, and outcomes of public libraries; information behavior on social media; and bibliometrics. She has published in College & Research Libraries, Journal of Documentation, Journal of the Association for Information Science and Technology, Library & Information Science Research, and Scientometrics, among others."),
    20 => array(
        "ime" => "Kyung-Sun",
        "prezime" =>"Kim",
        "fotka" => "KSun_KimPhoto.jpg",
        "cv" => "K.Sun Kim is Professor at the Information School, University of Wisconsin-Madison. She holds a PhD from the University of Texas at Austin, USA and a MLIS from l’Universite de Montreal, Canada. Her research focuses on information behavior and user-centered information services/systems."),
    21 => array(
        "ime" => "EunYoung",
        "prezime" =>"Yoo-Lee",
        "fotka" => "EunYoung_Yoo-Lee_Photo.jpg",
        "cv" => "EunYoung Yoo-Lee is a professor in the school of School of Library and Information Sciences at North Carolina Central University.  She holds a Ph.D in Library and Information Studies from University of Wisconsin-Madison. Her research areas include human information behaviors in diverse contexts, digital library and social media use, consumer health informatics and diversity education.  Her research has been published in journals including Journal of the Association for Information Science and Technology, Library Quarterly, College and Research Libraries, Reference Services Review, etc."),
    22 => array(
        "ime" => "Barbara",
        "prezime" =>"Kavčič",
        "fotka" => "Barbara_Kavcic_photo.jpg",
        "cv" => "Barbara Kavčič works as head of a library for cultural heritage in the Ministry of culture since 2009. She gives special attention to patron education, development of an international network for information and publication exchange. Her primary focus is on clients and building a strong cooperation network between institutions to provide the best service. She is passionate about introducing new trends in the library, and with that, she pushes for continual library transformation. She was a part of the executive committee in Section for special libraries at Slovenian Library Association in mandate 2013-2017 and is the current president of the Special library Section at Slovenian Library Association since 2017."),
    23 => array(
        "ime" => "Mirna",
        "prezime" =>"Gilman Ranogajec",
        "fotka" => "Mirna Gilman Ranogajec_Portrait_Image_Profile.jpg",
        "cv" => "Mirna Gilman Ranogajec is a teaching and research assistant at the Department of Information Sciences at the Faculty of Philosophy in Osijek, Croatia. She has participated in several international conferences as a member of the organizing committee such as ASIS&T 2015, LIDA 2018, BOBCATSSS 2019 and the European Summer School of Information Sciences ESSIS 2019. As a presenter she has participated in international conferences and regional conferences such as Publishing Trends and Contexts, Scientific Symposium \"Region, entrepreneurship, development\", the international conference \"Slavic-German Encounters in Literature, Language and Culture\", Libraries in the Digital Age (LIDA) and the annual symposium BOBCATSSS. She published scientific papers in the areas of visual and information literacy, information behavior, reading habits and interests while her primary areas of interest are children’s book publishing, reading habits and interests, user experience design and user behaviour."),
    24 => array(
        "ime" => "Ivanka",
        "prezime" =>"Stričević",
        "fotka" => "Ivanka_Stricevic_photo.jpg",
        "cv" => "Graduated in pedagogy and librarianship, obtained a MA degree in pedagogy, and a PhD degree in information and communication sciences, all from the University of Zagreb. University Professor from 2007, and Director General of the National and University Library in Zagreb from 2020. As the University professor she teaches at the pregraduate, graduate and postgraduate studies. Member of scientific conferences’ programme committees and national and international professional associations. Published more than 70 papers, co-authored 10 studies and books, edited numerous publications on users of information, reading, information literacy and librarianship, and worked on four scientific and numerous expert projects."),
    25 => array(
        "ime" => "Alica",
        "prezime" =>"Kolarić",
        "fotka" => "Alica Kolaric_photo.jpg",
        "cv" => "Alica Kolarić obtained her MA degree in philosophy and comparative literature (1999) and library and information science (2000) at the Faculty of Humanities and Social Sciences, University of Zagreb, Croatia. She earned a PhD degree in 2021 at the University of Zadar, with a dissertation entitled Understanding adolescent information behavior from the perspective of informed decision making process. Since 2020 she has been working at the Department of information sciences of the University of Zadar as a research assistant. She is a member of the Reading Committee of the Croatian Library Aassociation (2020 - ), as well as a corresponding member of IFLA - Libraries for Children and Young Adults Section (2019 - )."),
    26 => array(
        "ime" => "Kristina",
        "prezime" =>"Romić",
        "fotka" => "Kristina_Romic_Photo.jpg",
        "cv" => "Kristina Romić works at the Acquisition Department, National and University Library in Zagreb, Croatia. She graduated from the Faculty of Science, University of Zagreb in geography and history, and from the Faculty of Humanities and Social Sciences, University of Zagreb in information sciences (librarianship). She holds an MA in economy. From 2008 to 2013 she has worked as cataloguer at the National Bibliography Department (Retrospective Bibliography Section) of the National and University Library in Zagreb and is currently working at the Acquisition Department as senior librarian."),
    27 => array(
        "ime" => "Goranka",
        "prezime" =>"Mitrović",
        "fotka" => "Goranka_Mitrovic_Photo.jpg",
        "cv" => "Goranka Mitrović, is competent library adviser for academic and special libraries of Croatian institute for librarianship, National and University Library in Zagreb.
Her main interest are academic libraries, their manegament, cooporation, development and making of bibliometric analysis conected to scientific productivity of croatian academic and scientific society and alltoughether scientific activity.
She is a guest lecteruer at the Doctoral study in geography, Department of Geography at the Faculty of Science in Zagreb. She also holds lectures and workshops that are concerning knowlegde, technique and skills of online data base reashearch and evaluation of scientific work based on bibliometric and scientimetric references.
She published dosen papers in scinetific and expert magazines. She is a reviewer of croatian scientific and expert magazines for scientific papers concerning bibliometrical research and analysis."),
    28 => array(
        "ime" => "Lovela",
        "prezime" =>"Machala Poplašen",
        "fotka" => "Lovela_Machala-Poplasen_Photo.jpg",
        "cv" => "Lovela Machala Poplašen is a head librarian at the Andrija Štampar Library, School of Public Health, School of Medicine, University of Zagreb, Croatia. She is a LIS PhD candidate at the University of Zagreb, Faculty of Humanities and Social Sciences. Her research interests are: information literacy, open science, scholarly communication and webometrics."),
    29 => array(
        "ime" => "Ljiljana",
        "prezime" =>"Poljak",
        "fotka" => "ljiljana_poljak_photo.jpg",
        "cv" => "Ljiljana Poljak holds a degree in Library and Information Science from the University of Zadar and is currently a PhD student at the same university. She works as a librarian at the University of Split Library in the Department of Research Services and Development where her responsibilities include analysis of scientific productivity, web development, institutional repository management and Open Science advocacy. She is also a coordinator for Research Data and Research Data Alliance (RDA) activities for the University of Split Library. Previously she worked as a teaching assistant at the Department of Information Sciences at the University of Zadar teaching courses in Library Services and Management and Information Society. "),
    30 => array(
        "ime" => "Maura",
        "prezime" =>"Seale",
        "fotka" => "Maura_Seale_Photo.jpg",
        "cv" => "Maura Seale is the History Librarian at the University of Michigan. She edited, with Karen P. Nicholson, The Politics of Theory and the Practice of Critical Librarianship, which was published by Library Juice Press in March 2018. She has also written about critical librarianship, library pedagogy and information literacy, race and gender in librarianship, and the political economy of libraries. She welcomes comments @mauraseale on Twitter.  "),
    31 => array(
        "ime" => "Maja",
        "prezime" =>"Kuhar",
        "fotka" => "Maja_Kuhar_Photo.jpg",
        "cv" => "Maja Kuhar is a PhD student and young researcher at the Department of Library and Information Science and Book studies at the University of Ljubljana. Her master's degree was in the field of open access. Her PhD research focuses on the use of eye tracking for evaluation of bibliographic information systems. She is interested in how different interfaces influence user information behavior. "),
    32 => array(
        "ime" => "Randolf",
        "prezime" =>"Mariano",
        "fotka" => "Randolf Mariano_photo.png",
        "cv" => "Randolf Mariano is a Ph.D. student at the Department of Language and Culture under Media and Documentation Science Research Unit at UiT The Arctic University of Norway, advised by Prof. Andreas Vårheim. As a member of the research group \"LAMCOM - Libraries, Archives, and Museums in the Community\", Randolf is studying the role of cultural and innovation diplomacy towards LAMs' learning environments in providing educational, economic, and social opportunities to the civic public.

Before starting his Ph.D. at UiT, he worked as a Digital Engagement Librarian at the U.S. State Department's American Spaces and Korean Cultural Center in the Philippines. He studied both his Bachelor's and Master's degree in Library and Information Science at the University of the Philippines."),
    33 => array(
        "ime" => "Diana",
        "prezime" =>"Floegel",
        "fotka" => "Diana_Floegel_photo.jpeg",
        "cv" => "Diana Floegel earned their Ph.D. at the Rutgers School of Communication and Information. Their research examines phenomena surrounding people’s information creation practices, sociotechnical assemblages, and social justice in information institutions like libraries. They have published in Library and Information Science Research, Journal of Documentation, Journal of the Association for Information Science and Technology, and more. Diana can be contacted at diana.floegel@rutgers.edu. "),
    34 => array(
        "ime" => "Tamara",
        "prezime" =>"Heck",
        "fotka" => "Tamara_Heck_Photo.JPG",
        "cv" => "Tamara Heck is a researcher at the Information Center for Education at DIPF | Leibniz Institute for Research and Information in Education in Frankfurt, Germany. She investigates how people seek information and online resources and how infrastructures and tools influence their behaviour and practices. Her research includes information seeking behaviour and the design of user-centred informational systems, as well as conceptions and behaviour of open science practices in research and education."),
    35 => array(
        "ime" => "Zbigniew",
        "prezime" =>"Gruszka",
        "fotka" => "zbigniew_gruszka_photo.jpg",
        "cv" => "Zbigniew Gruszka – Ph.D., assistant professor at University of Lodz (Poland) in the Department of Information, Library and Book Science. Areas of interest: library management and strategies, regional studies, digital literacy. Selected publications: What May Library and Information Science Offer to Personal Information Management? Zagadnienia Informacji Naukowej 2020 nr 2, Institutional contexts of LIS education in Poland Education for Information 2020, Deregulation of the librarian profession in Poland: the course and the consequences (co-author  M. Antczak). In: Information and technology transforming lives: connection, interaction, innovation: Proceedings of International Symposium Bobcatsss, Osijek 2019."),
    36 => array(
        "ime" => "Tjaša",
        "prezime" =>"Jug",
        "fotka" => "Tjasa_Jug_Photo.jpg",
        "cv" => "Tjaša Jug is currently employed as assistant and librarian at the University of Ljubljana, Faculty of Arts, Department of Library and Information Science and Book Studies. In her PhD research she focused on publisher metadata and the potential of the Library Reference Model (LRM) in various book market contexts, such as book description, metadata in online bookstores and organization of online reviews. "),
    37 => array(
        "ime" => "Andreas",
        "prezime" =>"Vårheim",
        "fotka" => "Andreas+Varheim+HSL+personkort.jpeg",
        "cv" => "Andreas Vårheim is a Professor of Media and documentation Studies/Library and information science in the Department of Language and Culture at the University of Tromsø The Arctic University of Norway. His present research covers information policy, LAM institutional development, and LAM in community development."),
    38 => array(
        "ime" => "Roswitha",
        "prezime" =>"Skare",
        "fotka" => "Roswitha_Skare_photo.jpg",
        "cv" => "Roswitha Skare is a Professor of Media and documentation Studies in the Department of Language and Culture at the University of Tromsø The Arctic University of Norway. Her present research covers LAM institutions, paratext and document theory."),
    39 => array(
        "ime" => "Katarina",
        "prezime" =>"Švab",
        "fotka" => "Katarina_Svab_Photo.jpg",
        "cv" => "Katarina Švab is Assistant Professor at the University of Ljubljana (Faculty of Arts, Department of Library and Information Science and Book Studies). Before becoming a young researcher, she worked as a school librarian and teacher at primary school. In 2016, she defended her dissertation entitled: \"Attributes and Relationships in Bibliographic Information Systems.\" Her research interests include library catalogues, library catalogue users, and public library services. She is a co-author of the university textbook Organization of Library Collections (2019)."),
    40 => array(
        "ime" => "Tammy",
        "prezime" =>"Westergard",
        "fotka" => "TammyWestergard_NV_SANDI_ProjectDirector_mug.jpg",
        "cv" => "Tammy Westergard has advanced job recovery, STEM learning, career credentialing, and workforce training adapted to Nevada’s economic needs. Her work to modernize workforce programs through deployment of virtual reality resources has led to grant funding for new job seeker services. As Project Director for the US Department of Education’s Reimagine Workforce Preparation Grant Program her multiyear charter includes additional integration of 3D and virtual reality content to advance labor market literacy.  Through Nevada’s public libraries equitable access to these powerful resources to upskill into living wage jobs is amplified. Prior to this, Tammy served as Nevada State Librarian and Division Administrator at the Nevada State Library, Archives and Public Records. Tammy is a member of the American Library Association, Public Library Association, Nevada Library Association, Association of Records Managers and Administrators, and Beta Phi Mu International Library & Information Studies Honor Society. She also serves as an International Advisory Board Member for the Vaclav Havel Library Foundation."),
    41 => array(
        "ime" => "Athena",
        "prezime" =>"Salaba",
        "fotka" => "Athena_Salaba_Photo.JPG",
        "cv" => "Athena Salaba is a Professor in the School of Information (iSchool) at Kent State University, USA. Her teaching and research areas include organization of information, knowledge organization systems, metadata, presentation of metadata through system interfaces, and user experience when interacting with bibliographic information and interfaces. She has published books, peer-reviewed journal articles and conference papers, and presented on these topics internationally. She is the Chair of the IFLA Subject Analysis and Access Section and serves as the Treasurer for the International Society for Knowledge Organization (ISKO). She has been involved in the development and review of the FRSAD and LRM bibliographic conceptual models. She holds a Ph.D. in Library and Information Studies from the University of Wisconsin-Madison."),
    42 => array(
        "ime" => "Deborah",
        "prezime" =>"Hicks ",
        "fotka" => "Hicks_Photo.jpg",
        "cv" => "Deborah Hicks is an assistant professor at the School of Information at San Jose State University. She holds a PhD from the University of Alberta. Her research is focused on the professional identity of information professionals and how this identity informs the work they do, the organizations they run, and the relationships and communities they build. Her research has been published in journals including Library Quarterly, Library Trends, and Canadian Journal of Information and Library Sciences. She has presented at conferences in North American and Europe. "),
    43 => array(
        "ime" => "Tanja",
        "prezime" =>"Merčun ",
        "fotka" => "Tanja_Mercun_Photo.jpg",
        "cv" => "Dr. Tanja Merčun is an assistant professor of Library and Information Science at University of Ljubljana (Slovenia). Her research focuses on the design of bibliographic information systems, human-computer interaction and user experience in virtual and physical spaces. She teaches courses on research methods, information retrieval systems and organization of information resources. She is an active member of IFLA and a reviewer for several scholarly journals."),
    44 => array(
        "ime" => "Crystal",
        "prezime" =>"Fulton",
        "fotka" => "Crystal_Fulton.png",
        "cv" => "Crystal Fulton is an Associate Professor at University College Dublin, Ireland, where she studies the social interactions among people, information, and communication in daily life settings. She is this year's Chair of ASIS&T's European Chapter."),
    45 => array(
        "ime" => "Daniel",
        "prezime" =>"Martínez-Ávila",
        "fotka" => "Daniel_Martínez_Avila.jpg",
        "cv" => "Daniel Martínez-Ávila is assistant professor at the Department of Library and Information Science, Universidad Carlos III de Madrid (UC3M), Spain, and also teaches at the Graduate School of Information Science at São Paulo State University (UNESP), Brazil. He is the current editor of the ISKO's Advances in Knowledge Organization series and member of the editorial board of several internal journals. His research interests include knowledge organization, scholarly communication and social issues of Library and Information Science."),
    46 => array(
        "ime" => "Fernanda",
        "prezime" =>"Bochi",
        "fotka" => "Fernanda_Bochi.jpg",
        "cv" => "Fernanda Bochi received her bachelor's degree in Library Science and her Master's in Communication and Information from Federal University of Rio Grande do Sul (UFRG), Brazil. She is currently a doctoral student in Information Science at Sao Paulo State University, Brazil"),
    47 => array(
        "ime" => "Fidelia",
        "prezime" =>"Ibekwe",
        "fotka" => "Fidelia_Ibekwe.png",
        "cv" => "Fidelia Ibekwe is a Full Professor at the School of Journalism & Communication, Aix-Marseille University (France). Her research interests are centred on Critical Race Theory applied to Library and Information Studies, Race relations in Higher Education Institutions (HEIs), History & Foundations of Information Science, Knowledge organisation, Information Representation, Mapping Knowledge Domains & Open science. She is currently the Editor in Chief of Education for Information. Interdisciplinary journal of information studies."),
    48 => array(
        "ime" => "Karen",
        "prezime" =>"Nicholson",
        "fotka" => "KAREN_NICHOLSON_Photo.jpeg",
        "cv" => "Dr. Karen P. Nicholson is Manager, Information Literacy, at the University of Guelph and a lecturer at the Faculty of Information & Media Studies at Western University, both in Ontario, Canada. Her research focuses on information literacy, academic libraries, and time-space. She has published in College & Research Libraries, Library Trends, and the Journal of Critical Library and Information Studies. Her article “On the Space/Time of Information Literacy, Higher Education, and the Global Knowledge Economy” received the Library Juice Press Paper of the Year Award in 2019. From 2011-2018, Dr. Nicholson served as a facilitator with the Association of College & Research Libraries’ Information Literacy Immersion programs."),
    49 => array(
        "ime" => "Jaroslav",
        "prezime" =>"Šušol",
        "fotka" => "Jaroslav Susol Photo.JPG",
        "cv" => "Jaroslav Šušol is a professor at the Department of Library and Information Science, Faculty of Arts, Comenius University in Bratislava. He studied in Bratislava and Brussels (Université Libre), participated in short-term study and research stays in Lisbon, Aberdeen, Washington, D.C., Urbana-Champaign, Stockholm. In his research and lecturing, he concentrates on the topics related to the impact of information technology on the processes of communication. He worked on several national and international projects, both in the area of research (library systems and automation, digitisation and digital libraries, electronic and computer-mediated communication, changes in copyright legislation in the digital environment, human information behaviour) and academic management (UNICA – Network of Universities from the Capitals of Europe, CEI/UN – Central European Initiative University Network). At present, he is predominantly interested in the topics of information/publication behaviour, implementation of bibliometric methods in the area of scientific research evaluation and the challenges of privacy in the domain of digital communication."),
    50 => array(
        "ime" => "Joe",
        "prezime" =>"Mocnik",
        "fotka" => "Joe_Mocnik_Photo.jpg",
        "cv" => "Josip (Joe) Mocnik is a Dean of Libraries at North Dakota State University, Fargo, the state’s land grant university. He is originally from Croatia and has his M.A. in Library and Information Studies from University College London, UK, and Ph.D. in history from Bowling Green State University. He previously served as a Fulbright Scholar. In addition to his administrative activities, he is actively promoting all aspects of library innovation, especially in the areas of digital scholarship, data services, and effective data practices. He is passionate about social justice, community service, internationalization, and lifelong learning. He is active in a variety of professional organizations. "),
    51 => array(
        "ime" => "Amy",
        "prezime" =>"Kimura",
        "fotka" => "kimura.JPG",
        "cv" => "Amy Kimura is the Web Services Librarian at Rutgers, the State University of New Jersey, USA, where her primary goal is to build and maintain a user-friendly, accessible web presence that is informed by the needs and behaviors of library users from across the Rutgers community. She has published and presented on issues around accessibility, user experience design, and information-seeking behavior. Prior to settling at Rutgers, she was a librarian for Special Collections at a music conservatory, and her background as a musicologist has led her around the world, living and conducting research in the Netherlands and Indonesia."),
    52 => array(
        "ime" => "Kornelija",
        "prezime" =>"Petr Balog",
        "fotka" => "Petr Balog_slika.jpg",
        "cv" => "Dr. Kornelija Petr Balog is a Professor at Department of Information Sciences, Faculty of Humanities and Social Sciences, University of Osijek, Croatia. She obtained her PhD in Information Science (2004) from Zagreb University, Croatia. Her research interests are in information retrieval, performance measurement, information literacy, and organisation of information. Currently, she is working on the projects on older adults and their usage of ICT and information needs of Alzheimer's disease patients and their caregivers. She can be reached at kpetr@ffos.hr."),
    53 => array(
        "ime" => "Rahmi",
        "prezime" =>" ",
        "fotka" => "Rahmi_photo.png",
        "cv" => "Dr. Rahmi is an Assistant Professor in the Department of Library and Information Science, Faculty of Humanities, Universitas Indonesia, Indonesia. Her research focuses on human-centred aspects of information behaviour. Recent projects include (Disaster-related) Human-Information Behaviour, Corporeal/Embodied Information, Computational Social Science, Documentation Studies, and Crisis Informatics. She received her M.Sc and PhD degrees from the Graduate School of Library, Information and Media Studies, University of Tsukuba, JAPAN, in 2015 and 2019, respectively. Dr Rahmi is the chair of Kappa Sigma Kappa Indonesia (KSKI) and a co-founding member of the Digital Humanities research group in the Faculty of Humanities, Universitas Indonesia. You can reach Rahmi at rahmi.ami@ui.ac.id"),
    54 => array(
        "ime" => "Vanessa",
        "prezime" =>"Kitzie",
        "fotka" => "Vanessa_Kitzie.jpg",
        "cv" => "Dr. Vanessa Kitzie studies the information practices of marginalized groups, with a focus on individuals identifying as LGBTQ+. Her research findings inform how information centers, such as libraries, and systems can better serve these individuals. Kitzie's  work is interdisciplinary, spanning library and information science, communication, sociology, and critical studies."),
    55 => array(
        "ime" => "Yulistiana",
        "prezime" =>"Prasetya",
        "fotka" => "Yulistiana_Prasetya_photo.jpg",
        "cv" => "Yulistiana Prasetya is a student of library science, Faculty of Humanities, University of Indonesia. Yulis was active in organizations, especially in the creative media division, and took part in an internship as a visual designer in 2020. Yulis has participated in scientific writing competitions. In 2018, her team’s article published in the Jurnal Merah Putih, volume 5, ISSN 2339-2460. Yulis has also been a self-freelancer in design and video editing. Yulis has been interested in the scientific world and the digital world since high school by joining the Scientific youth group’s extracurricular activities and being a member of the robotic electronic programming division and serving as treasurer for a year. During her time as a member of the youth scientific group, Yulis participated in several activities, including the 2016 Intel-LIPI Youth Innovation Day."),
	56 => array(
        "ime" => "Ana Lúcia",
        "prezime" =>"Terra",
        "fotka" => "AnaLuciaTerraFoto.jpg",
        "cv" => "Ana Lúcia Terra is Assistant Professor at University of Coimbra, Department of Philosophy, Communication and Information, since November 2020. From 2002 to October 2020, she was Adjunct Professor at Polytechnic Institute of Porto. She holds a PhD in Information Science (2009) from University of Coimbra (Portugal). She holds a degree in History, a master degree in Modern History and has a Postgraduate Course in Libraries and Archives from the same university. She has received in 2009 the Raul Proença Prize, sponsored by the Directorate-General for Books and Libraries, distinguishes works in the area of Library Science, Archives and Information Science.Her main research interests include information behaviour, information management and knowledge organization."),
	57 => array(
        "ime" => "Bahia",
        "prezime" =>"Halawi",
        "fotka" => "Bahia_Halawi_photo.JPG",
        "cv" => "Bahia Halawi is a data scientist and an information science PhD candidate at Aix Marseille, France. She obtained her master’s degree from the Lebanese American University after majoring in computer science and mathematics. Her research interests include social media analysis, recommendation engines and digital media practices. She helped in the developing of CognativeX, a smart recommendation engine that serves the Arabic online landscape and she also took part in many multidisciplinary projects that focus on analyzing online behavior on social media platforms. She participated in many conferences and event all across the globe and currently leads the digital transformation journey of AlMayadeen TV online, which is one of the biggest platforms in the MENA region."),
    58 => array(
        "ime" => "Boris",
        "prezime" =>"Bosančić",
        "fotka" => "Bosancic_photo.jpg",
        "cv" => "Boris Bosančić, PhD is an associate professor at the Department of Information Sciences, Faculty of Humanities and Social Sciences, University of Osijek, Croatia. In 1996 he graduated Faculty of Mechanical Engineering Faculty, University of Osijek, dislocated in Slavonski Brod. He got his BA in Library and Information Science at Faculty of Philosophy, University of Zagreb in 2003. In 2009. he obtained his MA in Library and Information Science at Faculty of Philosophy, University of Zagreb with thesis \"Knowledge bases of online reference services\". In 2011 he received Ph.D. in Information Science Department of Information Sciences University of Zadar with dissertation \"Text encoding of Croatian old books using TEI\". His interest are theory of information, metadata, semantic web (linked data), markup languages, etc. He has published several scientific papers as well as display and participated with a presentation at international and national scientific meetings."),
    59 => array(
        "ime" => "John",
        "prezime" =>"MacLeod",
        "fotka" => "John_MacLeod_photo.jpg",
        "cv" => "John MacLeod is the executive director of XRLibraries, a leading company integrating XR technology in libraries and schools working with state and local libraries to implement strategies for deploying augmented, virtual and 360 vr technology and programs. Over 200 VR systems have been installed in underserved libraries in California and Nevada, making this the largest VR installation in public library networks. He is a partner in Nevada State Library's Career Pathways Program providing the College of Southern Nevada -the first-in-the-world dialysis technician training using 3D and virtual reality. He continues to build a national clearinghouse for libraries to share best practices in the use of XR technologies in libraries."),
    60 => array(
        "ime" => "Laura",
        "prezime" =>"Grzunov",
        "fotka" => "Laura_Grzunov_photo.jpg",
        "cv" => "Laura Grzunov (research assistant) works as an assistant at the Department of Information Sciences at the University of Zadar. She teaches seminars and exercises in the courses Information Organization, Theory and Practice of Information Organization, Processing of Old and Rare Materials, Evaluation of information services and Information Collection Management. Since 2017, she has been an associate on the university project Digitization, Bibliographic Description and Research of Texts Written on Glagolitic, Croatian Cyrillic and Latin Scripts Until the End Of 19th Century in Zadar and Šibenik Area which is being carried out at the University of Zadar by Centre for Research in Glagolitism."),
    61 => array(
        "ime" => "Manfredi",
        "prezime" =>"La Manna ",
        "fotka" => "Manfredi_La_Manna_photo.jpg",
        "cv" => "Manfredi La Manna is a Reader in Economics at the University of St Andrews. He has a long-standing interest in scholarly communication and open access (he was one of the original signatories of the Budapest OA Initiative). He has presented papers on open access at several international conference and published articles on OA in several journals. As director of the BitViews Project he is organizing a decentralized international network of libraries to create a new route to Open Access, deploying blockchain technology to provide new incentives to researchers to promote universal OA."),
    62 => array(
        "ime" => "Marijana",
        "prezime" =>"Tomić",
        "fotka" => "Marijana_Tomic_photo.jpg",
        "cv" => "Dr Marijana Tomić is Associate Professor at the Department of Information Sciences and a Head of a scientific Centre for Research in Glagolitism of the University of Zadar, Croatia. She teaches courses in the theory and practice of information organization, cataloguing of old and rare books, book history, and the digital humanities. She has published a book, in addition to a number of papers and book chapters. She is a chair of an interdisciplinary scientific project Digitization, Bibliographic Description and Research of Texts Written on Glagolitic, Croatian Cyrillic and Latin Scripts Until the End Of 19th Century in Zadar and Šibenik Area which is being carried out at the University of Zadar by Centre for Research in Glagolitism in co-operation with Vestigia Manuscript Research Centre of the University of Graz, Austria, and an associate in a number of scientific and research projects."),
    63 => array(
        "ime" => "Martina",
        "prezime" =>"Dragija Ivanović",
        "fotka" => "Martina_Dragija_Ivanovic_photo.jpg",
        "cv" => "Martina Dragija Ivanović is an assistant professor at the Department of Information Science, University of Zadar, Croatia. Her research interest includes evaluating impact of a public libraries in society, public library services in rural areas especially deprived places.  Her research is also focused on the position of information institutions in information society and reading studies and research methods in LIS. Previously she worked as a librarian in Public Library Zadar as coordinator for the development of library network in Zadar County. She is the recipient of the Ljerka Markić Čučuković Award, awarded to the best LIS student at University of Zagreb (1999), the Croatian Librarians' Association (CLA) award Eva Verona which is presented to young librarians, CLA members, for their outstanding dedication to work (2008) .  She can be reached at mdragija@unizd.hr."),
    64 => array(
        "ime" => "Michaela",
        "prezime" =>"Melicherová",
        "fotka" => "Melicherova_Michaela.jpg",
        "cv" => "Mgr. Michaela Melicherová, PhD.  MM was born in September ´91 in Bratislava (Slovakia), where in 2011 began studying at the Department of Library and Information Science (Comenius University in Bratislava, Faculty of Arts). She completed her bachelor's degree by defending a thesis focused on standards and technologies in the context of digitization and preservation of text documents. She continued studies at the Department of LIS, during which she dealt with the related topic, long-term archiving of digital objects in institutional repositories. She elaborated the topic as a diploma thesis, for which she also received an award at the student scientific conference in the section Library and Information Science in 2016. In the same year, she was accepted to the position of an internal doctoral student at the Department of LIS, where, in addition to study and publishing activities, taught subjects focused on information in scholarly communication, academic writing and more. She also participated in the editorial of the Proceedings of Library and Information Science (Vol. 27 and 28), which the Department of LIS publishes regularly. During her doctoral studies, she became interested in the topic of alternative ways of assessing of science. In 2020 she defended her dissertation titled Application of alternative bibliometric indicators in the evaluation of science under the leadership of prof. Jaroslav Šušol. Throughout her studies, she gained practice in institutions such as The Bratislava City Library, The Documentation Centre/Library of National Bank of Slovakia, or at Faculty of Mathematics, Physics, and Informatics (Comenius University in Bratislava), where she still works as a librarian. michaela.melicherova@uniba.sk"),
    65 => array(
        "ime" => "Gary P.",
        "prezime" =>"Radford ",
        "fotka" => "Gary_Radford_CV.jpg",
        "cv" => "Gary P. Radford (Ph. D., Rutgers University) is Professor of Communication and Chairperson of the Department of Communication at Fairleigh Dickinson University, Madison, New Jersey, USA.  Dr. Radford’s research focuses on the philosophical and critical treatments of communication processes, drawing widely from the work of Michel Foucault. Dr. Radford serves as the editor of The Atlantic Journal of Communication, a fully blind- and peer-reviewed scholarly journal  concerned with the study of communication theory, practice and policy. He is the author of four books including: “Library conversations: Reclaiming interpersonal communication theory for understanding professional encounters” (with Marie L. Radford), “On the Philosophy of Communication,” and “On Eco.”"),
    66 => array(
        "ime" => "Gabriel ",
        "prezime" =>"Schneider",
        "fotka" => "210322_G_Schneider_photo.jpg",
        "cv" => "Gabriel Schneider currently works as a project employee in the projects “Movebank 2.0” and “BioDATEN” as part of the team Open Science at the Communication, Information, Media Centre (KIM) of the University of Konstanz. He holds a M.Sc. in Information Science with a focus on Library Science from Darmstadt University of Applied Sciences. His main interests lie in the fields of research data management, metadata and repositories."),
    67 => array(
        "ime" => "Rachel ",
        "prezime" =>"Pierce",
        "fotka" => "Pierce image.JPG",
        "cv" => "Rachel Pierce is a senior lecturer at the Swedish School of Library and Information Science at the University of Borås. She has a PhD in women’s history from the University of Virginia and an MSc in Library and Information Science from the University of Borås. Her publications include articles on the politics of sexuality and feminism during the Cold War and articles on digitized photography and metadata, with a focus on feminist descriptive practices. She also conducts research on the relationship between the physical and the digital archive. Pierce is the coordinator for the international master’s program in Library and Information Science, Digital Libraries and Information Services at the Swedish School of Library and Information Science, housed at the University of Borås."),
    69 => array(
        "ime" => "Sarah",
        "prezime" =>"Barriage",
        "fotka" => "Sarah_Barriage_Photo.jpg",
        "cv" => "Sarah Barriage is an Assistant Professor in the School of Information Science at the University of Kentucky. She completed her PhD in Communication, Information, and Library Studies in the School of Communication & Information at Rutgers, the State University of New Jersey. Her research focuses on the information practices of children and youth with a particular focus on early childhood, as well as issues of social justice as they relate to children’s librarianship and information institutions. She is also interested in developing and implementing qualitative research methods that privilege participants' voices, including participatory and arts-based methods. "),
    68 => array(
        "ime" => "Elena",
        "prezime" =>"Maceviciute",
        "fotka" => "elena1.jpeg",
        "cv" => "Prof. Elena Maceviciute, Deputy Editor Elena Maceviciute is Professor at the Swedish School of Library and Information Studies, University of Boras, Sweden and Professor in the Faculty of Communication, Vilnius University, Lithuania. Her research areas include reference work, information and communication needs, international and intercultural communication, and information management. She has been involved in big research projects of the European Union as well as nationally financed research in Sweden and Lithuania. She has led the international Master's programme Digital Library and Information Services for 10 years and has been involved in other educational activities. "),
    70 => array(
        "ime" => "Tatjana",
        "prezime" =>"Aparac Jelušić",
        "fotka" => "win_tatjana.jpg",
        "cv" => "Prof. dr. sc. Tatjana Aparac-Jelušić She started her university teaching and scientific career at the University of Zagreb, Department of Information Sciences, in 1983 as research assistant, and moved on to a position of an assistant professor, associate professor (after defending her PhD in the field of Information Sciences in 1991, and full professor (2001). Before retirement she was the Full Professor and Head of the University Department of Information Sciences at the University of Zadar, from 2007 to 2012, and Head of the Department of Information Sciences at the University of Osijek, from 2003 to 2007.  In 2008 she was appointed as the Dean of the PhD program Knowledge Society and the Information Transfer, University of Zadar. She taught as visiting professor in Eisenstadt, at the University of Graz, Austria and on several occasions she lectured short-term to graduate and PhD students at Boras University, Sweden. In October 2019 she was Visiting Professor at the Wellington University, New Zealand. She is an author of three books, nine chapters in books, over 120 research and professional papers (in Croatian, English and Italian), over 50 reviews and opinion papers. She has edited 25 books and serves at several international journals as a member of their editorial boards. She presented papers and gave invited or keynote speeches at many domestic and international conferences. She acted as a Chair of the American Society for Information Science and Technology / European Chapter (2003-2009), Euclid – European Association of LIS university departments (2008-2014) and Croatian Council on Libraries (2013 to present). She was a co-director of LIDA Conferences from 2000 to 2014 and was a member of PC for several international conferences such as CoLIS, ECDL, QQML2009, and a reviewer for ASIST, ALA, ECDL and several other international conferences. She received Kukuljević’s Award (Croatian highest award in LIS field) and Thompson/ISI Outstanding Teacher of Information Science 2006 – Award given by ASIST.<p align=\"center\" style=\"margin-top:50px\"><img src=\"fotke/cert_tatjana.jpg\"></p>"),
    71 => array(
        "ime" => "Mark",
        "prezime" =>"Anderson",
        "fotka" => "MarkPhoto.jpg",
        "cv" => "Mark Andersen is the Co-founder and CEO of Lifeliqe, a workforce development and education platform for students to learn visually in digital 3D. Lifeliqe was chosen to be a key partner in the first-in-the-U.S. workforce development workforce recovery initiative in Nevada. Lifeliqe's platform distributes the world's largest digital Science library available in interactive 3D models, augmented reality, and virtual reality. Mark focuses on expanding Lifeliqe's career exploration and job training learning resources into schools and libraries. He created Lifeliqe's partnership with the Nevada State Library launching XR into 16 Nevada libraries. Lifeliqe is partnering with the College of Southern Nevada's dialysis tech certification program where Lifeliqe is piloting a first-in-the-world VR simulation to train dialysis technicians. Previously he was the Business School Chairman at Anglo-American University where he also taught for five years. For the past twenty years Mark has worked as a marketing leader in tech startups in Silicon Valley. Before getting his MBA from Northwestern University (Kellogg) Mark co-founded a successful startup that grew to 120 employees."),
    72 => array(
        "ime" => "Drahomira",
        "prezime" =>"Cupar",
        "fotka" => "win_drahomira.jpg",
        "cv" => "Drahomira Cupar, Phd, is an assistant professor at the University of Zadar, Department of Information Sciences, Croatia. She obtained her PhD in Information science in 2013. She is currently working at Department of Information Sciences at the University of Zadar and teaching undergraduate and graduate courses in scholarly communication and academic writing, classification and subject indexing and sociology of reading. She served as a President of the Croatian Reading Association (CroRA) (2012-2014). She is a member of professional organizations: Croatian Library Association (CLA) (president of the Committee for subject indexing and classification), CroRA, ISKO (International Society for Knowledge Organization), IFLA (Section for subject indexing and access). She was involved in organization of several conferences and events organized by the Department (LIDA, PubMet, BOBCATSSS and summer schools) and is a co-director for the biennial international conference Libraries in the Digital Age (LIDA). She is recipient of the CLA award Eva Verona which is presented to best young LIS professionals (2012). She participates in the European project OPERAS and TRIPLE. "),
    73 => array(
        "ime" => "Cvijetin",
        "prezime" =>"Vidaković",
        "fotka" => "win_cvijetin.jpg",
        "cv" => "Cvijetin Vidaković is currently working as a Quality Assurance lead at the ”Five” company. He graduated and earned a master's degree in Publishing and Information technology at the Department of Information Sciences, Faculty of Humanities and Social Sciences, University of Osijek. In 2018, he won the award from the President of the University for his work on the 6th edition of “Libros” magazine. As a student, he participated on multiple conferences with papers, posters, etc. He participated with paper on 2018 BOBCATSSS conference held in Rita, Latvia with paper “The prescribed literature reading in the school curricula: Views and perceptions of Croation literature students at Osijek University, Croatia.” He participated in the 2018 FEIS symposium held in Pisa, Italy with the poster “MA program at Department of Information Sciences at Faculty of Humanities and Social Sciences, University of Osijek, Croatia”. He was a part of the Organizing Committee of several international and national conferences such as BOBCATSSS, LIDA, InfoDaska, DroidCon, WebCamp, etc. He was a part of multiple projects that were related to ICT being understandable and reachable to the community, projects like RoboCode and ICT Science Laboratory. At the last LIDA conference he participated in the Student showcase with a presentation on “Online Information Behaviour of Older Adults: Pilot-Study”. You can reach him on vidakovic.cvijetin@gmail.com.<p align=\"center\" style=\"margin-top:50px\"><img src=\"fotke/cert_ivona_cvijetin.jpg\"></p>"),
    74 => array(
        "ime" => "Ivona",
        "prezime" =>"Grgić",
        "fotka" => "win_ivona.jpg",
        "cv" => "Ivona Grgić is currently working as Data Administrator. In 2019, she graduated and earned a master's degree in Information sciences and Information technology (Department of Information Sciences in Osijek, Faculty of Humanities and Social Sciences Osijek, University of Josip Juraj Strossmayer in Osijek). In 2016, as part of the team, she won first place at the Koprivnica CODEFEST hackathon. As a student, she participated in the International Summer School of Information Sciences in Katlenburg, Germany (ESSIS 2017). At the international conference LIDA (Libraries in the digital age) in 2018, she participated in the Student showcase with a presentation on \"Online Information Behavior of Older Adults: Pilot-Study\". She participated in the 2018 Science Festival with a poster on the topic \"Mysterious Discoveries of Cryptography\". She was a member of the Organizing Committee of several national and international conferences (eg BOBCATSSS and InfoDASKA 2019). She participated in the project  \"Information Needs of Alzheimer Patients and Their Caregivers\". She was a member of the European Student Chapter belonging to ASIS&T (2019/2020).<p align=\"center\" style=\"margin-top:50px\"><img src=\"fotke/cert_ivona_cvijetin.jpg\"></p>"),
    75 => array(
        "ime" => "Marc",
        "prezime" =>"Rittberger",
        "fotka" => "Marc_Rittberger_photo.jpg",
        "cv" => "Marc Rittberger is Director of the Information Center for Education, a national research infrastructure unit at DIPF | Leibniz Institute for Research and Information in Education, a member of the Leibniz Association. He is a Professor of Information Management at the DIPF and at Darmstadt University of Applied Sciences. He studied Physics and Information Science, and has a Ph.D. in Information Science. Find details at: https://www.dipf.de/en/institute/staff/rittberger-marc "),
    76 => array(
        "ime" => "Sanda",
        "prezime" =>"Erdelez",
        "fotka" => "Sanda_Erdelez_photo.PNG",
        "cv" => "Dr. Sanda Erdelez is a Professor and Director at Simmons University School of Library and Information Science. She received her LL.B. and LL.M degrees from University of Osijek Law School (Croatia) and Ph.D. in information transfer from Syracuse University. Her research interests include human information behavior, human-computer interaction and usability evaluation in online environments and most recently information needs related to Alzheimer's disease. She published over 80 peer-reviewed scientific papers and gave more than 70 research presentations. She has been internationally recognized for her pioneering research on information encountering (the role of serendipity in information behavior). Her research has received funding from both corporate and government sources including Dell Inc., SBC Communication, Texas State Government, and NSF. In 2015, Dr. Erdelez received the Outstanding Contribution to Information Behavior Research Award from ASIS&T SIG Information Needs, Seeking and Use (USE) and also became a member of the SIG USE Academy of Fellows. "),
    77 => array(
        "ime" => "Tefko",
        "prezime" =>"Saracevic",
        "fotka" => "thumbnail_tefko2.jpg",
        "cv" => "Tefko Saracevic studied electrical engineering at the University of Zagreb, Croatia and completed his master (1962) and Ph.D. (1970) studies in information science at Case Western Reserve University, Cleveland, Ohio. He taught and conducted research at Case till 1985, when he moved to Rutgers. Saracevic was promoted to Professor II (highest academic rank at Rutgers Univ.) in 1991 and was Associate Dean from 2003 to 2006. Saracevic is a Distinguished Professor Emeritus since 2010. He continues by teaching a Digital Libraries course online every semester. Active internationally, particularly in relation to information problems in developing countries. For over a decade he was involved with the Rockefeller Foundation in design, deployment, and evaluation of compact high-quality, low-cost medical information systems in developing countries. He was a visiting professor at four universities abroad and also worked and consulted with a number of international organizations on development and evaluation of information systems and libraries. Saracevic has given seminars, lectures and courses, or consulted, and presented papers at international meetings in 43 countries, and was an invited keynote speaker at over a dozen international conferences. Co-chair from 2000 to 2014 of the biennial conference and course Libraries in the Digital Age (LIDA) held in Zadar, Croatia.<p align=\"center\" style=\"margin-top:50px\"><img src=\"fotke/cert_tefko.jpg\"></p>"),
    78 => array(
        "ime" => "Miriam",
        "prezime" =>"Ondrišová",
        "fotka" => "miriam_ondrisova_photo.JPG",
        "cv" => "Miriam Ondrišová studied computer science at the Slovak University of Technology in Bratislava. From 1994 she has been a member of the Department of Library and Information Science of Faculty of Arts, Comenius University, Bratislava. She received her PhD degree from the Comenius University in 2008. As a teacher she leads courses devoted to bibliometrics, database and information systems and information technology. Her research focuses on the field of bibliometrics, information literacy, data analysis and visualization. Comenius University in Bratislava, Department of Library and Information Science, Faculty of Arts, Gondova 2, 811 02, Slovak Republic. miriam.ondrisova@uniba.sk"),
    79 => array(
        "ime" => "Zrinka",
        "prezime" =>"Džoić",
        "fotka" => "win_zrinka.jpg",
        "cv" => "Zrinka Džoić works as an research assistant at the Department of Information Sciences since November 2020. She is also a PhD student at postgraduate doctoral program Knowledge Society and Information Transfer, University of Zadar. Previously she worked in the Office for Publishing, University of Zadar and as a librarian at the University of Zadar Library."),
    80 => array(
        "ime" => "Annemaree",
        "prezime" =>"Lloyd",
        "fotka" => "lloyd.jpeg",
        "cv" => " Annemaree is a Professor at the Department of Information Studies, University College London. She is a social science researcher with an interest in socio-cultural and practice theoretical perspectives; in landscape and visual methodology;  and in qualitative techniques. Her research explores  information literacies and contemporary information practices in formal and informal learning connected to workplaces, community settings and in higher education. Her current research program focuses on the intersection between information, learning, and the performance of practice. She is also interested in the connection between information literacies, social inclusion, and collaborative learning. Professor Lloyd is also engaged with theoretical work associated with the development of information practice, information literacy theory and landscape methodology."),
    81 => array(
        "ime" => "Ahmad M. ",
        "prezime" =>"Kamal",
        "fotka" => "kamal.jpg",
        "cv" => "Ahmad Kamal is a Senior Lecturer in the Department of Cultural Sciences at Linnaeus University, Sweden, where he teaches in both the Library and Information Science programme and the Digital Humanities programme. Ahmad's current research explore the uses of controlled vocabulary in information retrieval and the role of digital platforms in promoting social engagement in Italian academic libraries. His earlier work includes the study of migrants' digital space in Europe, the circulation of information in post-2011 Egypt, and the interventions of NGO-led libraries in India."),
    82 => array(
        "ime" => "Boris",
        "prezime" =>"Badurina",
        "fotka" => "bb.png",
        "cv" => "Boris Badurina is an associate professor at Department of Information Sciences, Faculty of Humanities and Social Sciences, University of Osijek, Croatia. He graduated from University of Zagreb with BA in Sociology and Ph.D in Information science. His research has been in a range from digital libraries development to the new technologies use, impact, and acceptance and lately social media and e-book use and perception. ")
    );

?>
